### ISSUE TITLE
Automatic installation of screenplain fails with `NameError: name 'subprocess' is not defined`

### ISSUE THREAD

**Issue by vilcans** [tin2tin/Blender_Screenwriter#24]
When tried to install the add-on in Blender 2.91 in Windows, I got this error when trying to enable it.  It seems like there is an automatic install that fails because subprocess isn't imported.

```Traceback (most recent call last):
  File "C:\Users\vilcans\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Blender_Screenwriter-master\__init__.py", line 45, in <module>
    import screenplain.parsers.fountain as fountain
ModuleNotFoundError: No module named 'screenplain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\vilcans\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Blender_Screenwriter-master\__init__.py", line 48, in <module>
    subprocess.check_call([pybin, '-m', 'pip', 'install', 'screenplain[PDF]'])
NameError: name 'subprocess' is not defined
```

As a workaround, I could install screenplain manually from the command line, and then I could enable the add-on.

**Comment by tin2tin** [comment]
Thanks. The import of that module was missing. Should be fixed now.
