### ISSUE TITLE
Formatting of title/meta data is missing

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/Blender_Screenwriter#5]
There is a bit of code to get the metadata which can be expanded.

**Comment by AndreaMonzini** [comment]
Hi, i tried   to add the `Title:` element in `fountain.py` and added in `Blender_Screenwriter.py`
If i use the `Title:` after scenes  the element is recognised and centered.
But it does not work with the actual title at the beginning of the fountain document, if i try to edit it:

```
Traceback (most recent call last):
  File "/home/linux/.config/blender/2.81/scripts/addons/Blender_Screenwriter.py", line 142, in execute
    F = fountain.Fountain(fountain_script)
  File "/home/linux/.config/blender/2.81/scripts/addons/fountain.py", line 52, in __init__
    self.parse()
  File "/home/linux/.config/blender/2.81/scripts/addons/fountain.py", line 62, in parse
    self._parse_head(script_head.splitlines())
  File "/home/linux/.config/blender/2.81/scripts/addons/fountain.py", line 74, in _parse_head
    self.metadata[open_key].append(line.strip())
KeyError: None

location: <unknown location>:-1
```

**Comment by tin2tin** [comment]
Added: https://github.com/tin2tin/Blender_Screenwriter/commit/34b66009b8581ef2b34839ec1dd8c42215c24405
