### ISSUE TITLE
Bug in Version 0.1  14/11/19  ~14:30

### ISSUE THREAD

**Issue by AndreaMonzini** [tin2tin/Blender_Screenwriter#9]
Testing with 2.81 and 2.82, error report in both ( yesterday version works) :
OS: GNU/Linux 

After pressing Preview and Refresh buttons:

`Traceback (most recent call last):
  File "/home/linux/.config/blender/2.81/scripts/addons/Blender_Screenwriter.py", line 320, in execute
    bpy.ops.scene.preview_fountain()
  File "/home/linux/App/blender-2.81-0a0d735acd6e-linux-glibc217-x86_64/2.81/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/linux/.config/blender/2.81/scripts/addons/Blender_Screenwriter.py", line 142, in execute
    F = fountain.Fountain(fountain_script)
AttributeError: module 'fountain' has no attribute 'Fountain'

location: /home/linux/App/blender-2.81-0a0d735acd6e-linux-glibc217-x86_64/2.81/scripts/modules/bpy/ops.py:201

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/linux/.config/blender/2.81/scripts/addons/Blender_Screenwriter.py", line 142, in execute
    F = fountain.Fountain(fountain_script)
AttributeError: module 'fountain' has no attribute 'Fountain'

location: <unknown location>:-1

location: <unknown location>:-1
`

**Comment by tin2tin** [comment]
Bad fountain file. Try now.

**Comment by AndreaMonzini** [comment]
Works! solved!
